logging:
  level:
    com.tencent: debug
devops:
  logging:
    path: /data/logs
    file-app: sample.log
    file-error: sample-error.log
  loadbalancer:
    gray:
      enabled: true
      meta-key: env
    local-prior:
      enabled: true

